/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icy.View;

import icy.Controller.DangKy_Controller;
import icy.Controller.QLNV_Controller;
import icy.Model.DangKyDTO;
import icy.Model.QLNV_DTO;
import icy.DAO.DangKy_DAO;
import icy.TrangChu_ICY;
import static icy.View.DangKy_View.dsdk;
import static icy.View.QLNV_View.NV;
//import icy.TrangChu_ICY;
//import icy.View.NhanVien_View;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
//import sql.TC;

/**
 *
 * @author Quan Phat Vinh Thanh
 */
public class QuanLyTK extends javax.swing.JFrame {

    public static QuanLyTK DK = new QuanLyTK();
    //QLNV_View dsnv = new QLNV_View();
    public static QuanLyTK tk = new QuanLyTK();
    DangKy_View DKGui = new DangKy_View();
    public static TrangChu_ICY TC = new TrangChu_ICY();
    QLNV_Controller bus = new QLNV_Controller();
    DangKyDTO dk = new DangKyDTO();
    DangKy_Controller busdk = new DangKy_Controller();
    ArrayList<DangKyDTO> dsdk = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form QuanLyTK
     */
    public QuanLyTK() {
        initComponents();
        DocDuLieu();
        showcbbMa();
        showcbbChucVu();

    }

    public void setComponentsNames() {
        btnXoa.setName("xoa");
        txtMK.setName("matkhau");
        lb_ReMK.setName("ReMk");
        btnSua.setName("sua");
        btnThem.setName("them");
        lbMK.setName("lbmk");
        lbMa.setName("lbma");
        lbTK.setName("lbtk");
        lb_CV.setName("lbcv");
        btnBack.setName("back");
        btnRe.setName("Re");
    }

    public void showcbbMa() {
        for (QLNV_DTO nv : QLNV_Controller.dsnv) {
            cbbChucVu1.addItem(nv.Ma);
        }
    }

    public void showcbbChucVu() {
        for (QLNV_DTO nv : QLNV_Controller.dsnv) {
            cbbChucVu.addItem(nv.ChucVu);
        }
    }
    public void setUser(String message) {
        lbU.setText(message);
    }
    public void DocDuLieu() {
        DangKy_Controller busdk = new DangKy_Controller();
        if (DangKy_Controller.dsdk == null) {

            busdk.DocDSDK();
        }
        Vector header = new Vector();
        header.add("Tên Tài Khoản");
        header.add("Mật khẩu");
        header.add("Mã nhân viên");
        header.add("Chức vụ");
        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }
        for (DangKyDTO dk : DangKy_Controller.dsdk) {
            Vector row = new Vector();
            row.add(dk.TaiKhoan);
            row.add(dk.MatKhau);
            row.add(dk.MaDK);
            row.add(dk.ChuVuDK);
            model.addRow(row);
        }
        tableTK.setModel(model);

    }

    public void ShowDSTaiKhoan(ArrayList<DangKyDTO> ds) {

        Vector header = new Vector();
        header.add("Tài khoản");
        header.add("Mật khẩu ");
        header.add("Mã nhân viên");
        header.add("Chức vụ");
        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }
        for (DangKyDTO tk : dsdk) {
            Vector row = new Vector();
            row.add(tk.TaiKhoan);
            row.add(tk.MatKhau);
            row.add(tk.MaDK);
            row.add(tk.ChuVuDK);
            model.addRow(row);
        }
        tableTK.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panQLTK = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbTC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbTK = new javax.swing.JLabel();
        lbMK = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        lb_ReMK = new javax.swing.JLabel();
        lb_CV = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        E_TK = new javax.swing.JLabel();
        E_MK = new javax.swing.JLabel();
        E_ReMK = new javax.swing.JLabel();
        E_CV = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        E_Ma = new javax.swing.JLabel();
        txtNhapLaiMK = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        cbbChucVu1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRe = new javax.swing.JButton();
        lb_KQTK = new javax.swing.JLabel();
        lbU = new javax.swing.JLabel();

        jLabel10.setText("jLabel7");

        jLabel11.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panQLTK.setBackground(new java.awt.Color(204, 204, 204));
        panQLTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));

        lbTC.setBackground(new java.awt.Color(0, 196, 235));
        lbTC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTC.setForeground(new java.awt.Color(102, 204, 255));
        lbTC.setText("Quản Lý Tài Khoản");

        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Tài Khoản", "Mật Khẩu", "Tên Nhân Viên", "Mã Nhân Viên", "Chức Vụ"
            }
        ));
        tableTK.setGridColor(new java.awt.Color(0, 153, 255));
        tableTK.setSelectionBackground(new java.awt.Color(51, 204, 255));
        tableTK.setShowGrid(false);
        tableTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTK);

        jPanel2.setBackground(new java.awt.Color(178, 237, 252));

        lbTK.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/utk.png"))); // NOI18N
        lbTK.setText("Tài khoản: ");

        lbMK.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/passwd.png"))); // NOI18N
        lbMK.setText("Mật khẩu");

        txtTK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTK.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtTK.setFocusCycleRoot(true);
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        txtTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTKKeyPressed(evt);
            }
        });

        lb_ReMK.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lb_ReMK.setText("Nhập lại mật khẩu: ");

        lb_CV.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lb_CV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/vitri.png"))); // NOI18N
        lb_CV.setText("Chức vụ: ");

        cbbChucVu.setForeground(new java.awt.Color(0, 0, 255));
        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>" }));
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });
        cbbChucVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbChucVuKeyPressed(evt);
            }
        });

        E_TK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_TK.setForeground(new java.awt.Color(255, 51, 51));

        E_MK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_MK.setForeground(new java.awt.Color(255, 51, 51));

        E_ReMK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_ReMK.setForeground(new java.awt.Color(255, 51, 51));

        E_CV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_CV.setForeground(new java.awt.Color(255, 51, 51));

        lbMa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/ID.png"))); // NOI18N
        lbMa.setText("Mã nhân viên: ");

        E_Ma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E_Ma.setForeground(new java.awt.Color(255, 51, 51));

        txtNhapLaiMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhapLaiMKKeyPressed(evt);
            }
        });

        txtMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMKKeyPressed(evt);
            }
        });

        cbbChucVu1.setForeground(new java.awt.Color(0, 0, 255));
        cbbChucVu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GD00" }));
        cbbChucVu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVu1ActionPerformed(evt);
            }
        });
        cbbChucVu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbChucVu1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMK)
                            .addComponent(lbTK))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_ReMK)
                        .addGap(18, 18, 18)
                        .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMa)
                            .addComponent(lb_CV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(E_ReMK, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_TK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_MK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_CV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_Ma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTK)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_TK)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMK)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_MK)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ReMK)
                    .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_ReMK)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMa)
                    .addComponent(cbbChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_Ma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_CV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_CV)
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(231, 231, 231));

        btnXoa.setBackground(new java.awt.Color(255, 204, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/delete-account.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        btnXoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnXoaKeyPressed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 204, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/add.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        btnThem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnThemKeyPressed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/maintenance.png"))); // NOI18N
        btnSua.setText("Đổi Mật Khẩu");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        btnSua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSuaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(231, 231, 231));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/back.png"))); // NOI18N
        btnBack.setText("Trở về");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRe.setBackground(new java.awt.Color(231, 231, 231));
        btnRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/re.png"))); // NOI18N
        btnRe.setBorder(null);
        btnRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReActionPerformed(evt);
            }
        });

        lb_KQTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_KQTK.setForeground(new java.awt.Color(255, 51, 0));

        lbU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icy/HinhAnh_ICY/TrangChu/profile-user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbU, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_KQTK, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRe)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lbTC, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lbU, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTC)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnRe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_KQTK, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout panQLTKLayout = new javax.swing.GroupLayout(panQLTK);
        panQLTK.setLayout(panQLTKLayout);
        panQLTKLayout.setHorizontalGroup(
            panQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panQLTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panQLTKLayout.setVerticalGroup(
            panQLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String ma = cbbChucVu1.getSelectedItem().toString();
        int i = tableTK.getSelectedRow();
        if (i >= 0) {
            busdk.xoaTK(ma);
            DangKy_Controller.dsdk.remove(i);
            model.removeRow(i);
            tableTK.setModel(model);
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            txtMK.setText("");
            txtNhapLaiMK.setText("");
            cbbChucVu1.setSelectedItem(dk.MaDK);
            cbbChucVu.setSelectedItem(dk.ChuVuDK);
        } else
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn tài khoản cần xóa");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

           String x = null;
        for (QLNV_DTO nv : bus.dsnv) {
            if (cbbChucVu1.getSelectedItem().toString().equals(nv.Ma)) {
                x = nv.ChucVu;
            }
        }
        Pattern uname = Pattern.compile("^[a-zA-Z0-9]{3,20}$");
        Pattern pass = Pattern.compile("^[a-zA-Z0-9]{3,20}$"); //8
        if (busdk.ID(cbbChucVu1.getSelectedItem().toString()) == true) {
            E_Ma.setText("Nhân viên này đã có tài khoản");
        } else if (busdk.checkTK(txtTK.getText()) == false) {
            E_TK.setText("Tên tài khoản đã tồn tại");
            E_Ma.setText("");
        } else if (!uname.matcher(txtTK.getText()).find()) {
            E_TK.setText("Tên tài khoản phải từ 3 đến 20 ký tự");
            E_Ma.setText("");
        } else if (!pass.matcher(txtMK.getText()).find()) {
            E_MK.setVisible(true);
            E_MK.setText("Mật khẩu phải từ 3 đến 20 ký tự");
            E_TK.setText("");
            E_Ma.setText("");
        } else if (txtMK.getText().equals(txtNhapLaiMK.getText()) == false) {
            E_ReMK.setVisible(true);
            E_MK.setText("");
            E_TK.setText("");
            E_Ma.setText("");
            E_ReMK.setText("Mật khẩu không hợp lệ");
        } else if (!cbbChucVu.getSelectedItem().toString().equals(x)) {
            E_CV.setVisible(true);
            E_CV.setText("Chức vụ không hợp lệ");
            E_ReMK.setText("");
            E_MK.setText("");
            E_TK.setText("");
            E_Ma.setText("");
        }
        else {
            DangKyDTO dk = new DangKyDTO();
            dk.ChuVuDK = cbbChucVu.getSelectedItem().toString();
            dk.MaDK = cbbChucVu1.getSelectedItem().toString();
            dk.TaiKhoan = txtTK.getText();
            dk.MatKhau = txtMK.getText();
            busdk.themTK(dk);
                    Vector header = new Vector();
                    header.add("Tên Tài Khoản");
                    header.add("Mật khẩu");
                    header.add("Mã nhân viên");
                    header.add("Chức vụ");
                    if (model.getRowCount() == 0) {
                        model = new DefaultTableModel(header, 0);
                    }
                    Vector row = new Vector();
                    row.add(dk.TaiKhoan);
                    row.add(dk.MatKhau);
                    row.add(dk.MaDK);
                    row.add(dk.ChuVuDK);
                    model.addRow(row);
                   tableTK.setModel(model);
            JOptionPane.showConfirmDialog(this, "Thêm thành công");
    }
    
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        int i = tableTK.getSelectedRow();
        if (i >= 0) {
            DangKyDTO dk = new DangKyDTO();
            dk.MaDK = cbbChucVu1.getSelectedItem().toString();
            dk.TaiKhoan = txtTK.getText();
            dk.MatKhau = txtMK.getText();
            dk.ChuVuDK = cbbChucVu.getSelectedItem().toString();
            if (!txtMK.getText().equals(txtNhapLaiMK.getText())) {
                E_ReMK.setText("Mật khẩu không hợp lệ");
            } else {
                busdk.sua(dk);
                E_ReMK.setText("");
                JOptionPane.showConfirmDialog(null, "Sửa thành công");
                DangKyDTO old = busdk.dsdk.set(i, dk);
                model.setValueAt(dk.TaiKhoan, i, 0);
                model.setValueAt(dk.MatKhau, i, 1);
                model.setValueAt(dk.MaDK, i, 2);
                model.setValueAt(dk.ChuVuDK, i, 3);
                tableTK.setModel(model);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn tài khoản cần sửa!!!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        NV.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReActionPerformed
          
        txtMK.setText("");
        txtNhapLaiMK.setText("");
        cbbChucVu.setSelectedIndex(0);

    }//GEN-LAST:event_btnReActionPerformed

    private void txtTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER) {
            txtMK.requestFocus();
        }
    }//GEN-LAST:event_txtTKKeyPressed

    private void txtNhapLaiMKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapLaiMKKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cbbChucVu1.requestFocus();
        }
    }//GEN-LAST:event_txtNhapLaiMKKeyPressed

    private void cbbChucVuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbChucVuKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER) {
            btnXoa.requestFocus();
        }
    }//GEN-LAST:event_cbbChucVuKeyPressed

    private void btnXoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnXoaKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == evt.VK_ENTER) {
            btnThem.requestFocus();
        }
    }//GEN-LAST:event_btnXoaKeyPressed

    private void btnThemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnThemKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER) {
            btnSua.requestFocus();
        }
    }//GEN-LAST:event_btnThemKeyPressed

    private void btnSuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSuaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER) {
            txtTK.requestFocus();
        }
    }//GEN-LAST:event_btnSuaKeyPressed

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucVuActionPerformed

    private void tableTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTKMouseClicked
        // TODO add your handling code here:
        int i = tableTK.getSelectedRow();
        if (i >= 0) {
            DangKyDTO dk = new DangKyDTO();
            dk = busdk.dsdk.get(i);
            if(dk.TaiKhoan.equals("giamdoc") && checkQuyenQLGD()==true ){
            txtTK.setText(dk.TaiKhoan);
            txtMK.setText(dk.MatKhau);
            cbbChucVu.setSelectedItem(dk.ChuVuDK);
            cbbChucVu1.setSelectedItem(dk.MaDK);
            E_CV.setText("");
            E_MK.setText("");
            E_Ma.setText("");
            E_ReMK.setText("");
            E_TK.setText("");
            txtNhapLaiMK.setText("");
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            }
            else if (dk.TaiKhoan.equals("giamdoc") && checkQuyenQLGD()==false ){
            txtTK.setText(dk.TaiKhoan);
            txtMK.setText(dk.MatKhau);
            cbbChucVu.setSelectedItem(dk.ChuVuDK);
            cbbChucVu1.setSelectedItem(dk.MaDK);
            E_CV.setText("");
            E_MK.setText("");
            E_Ma.setText("");
            E_ReMK.setText("");
            E_TK.setText("");
            txtNhapLaiMK.setText("");
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            }
            else if(!dk.TaiKhoan.equals("giamdoc")){
            txtTK.setText(dk.TaiKhoan);
            txtMK.setText(dk.MatKhau);
            cbbChucVu.setSelectedItem(dk.ChuVuDK);
            cbbChucVu1.setSelectedItem(dk.MaDK);
            E_CV.setText("");
            E_MK.setText("");
            E_Ma.setText("");
            E_ReMK.setText("");
            E_TK.setText("");
            txtNhapLaiMK.setText("");
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);

            }
               }
    }//GEN-LAST:event_tableTKMouseClicked

    private void cbbChucVu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucVu1ActionPerformed

    private void cbbChucVu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbChucVu1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cbbChucVu.requestFocus();
        }
    }//GEN-LAST:event_cbbChucVu1KeyPressed

    private void txtMKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtNhapLaiMK.requestFocus();
        }
    }//GEN-LAST:event_txtMKKeyPressed
     public boolean getTen(String s) {
        if (lbU.getText().equals(s)) {
            return true;
        } else {
            return false;
        }
    }
    public boolean checkQuyenQLGD() {
         for (DangKyDTO dk : DangKy_Controller.dsdk) {
            if (getTen(dk.TaiKhoan) && dk.ChuVuDK.equals("Giám đốc")) {
                return true;
            }
        }
        return false;

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tk.setVisible(true);
                tk.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E_CV;
    private javax.swing.JLabel E_MK;
    private javax.swing.JLabel E_Ma;
    private javax.swing.JLabel E_ReMK;
    private javax.swing.JLabel E_TK;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRe;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbChucVu1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMK;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbTC;
    private javax.swing.JLabel lbTK;
    private javax.swing.JLabel lbU;
    private javax.swing.JLabel lb_CV;
    private javax.swing.JLabel lb_KQTK;
    private javax.swing.JLabel lb_ReMK;
    private javax.swing.JPanel panQLTK;
    private javax.swing.JTable tableTK;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtNhapLaiMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
